name: Deploy online.yavsrg.net
on:
  push:
    branches: [ "main" ]
    paths: "online/server/Version.txt"
  workflow_dispatch:

concurrency:
  group: "server_deploy"
  cancel-in-progress: false

jobs:
  build_and_push:
    if: github.repository == 'YAVSRG/YAVSRG'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Unit tests
        run: dotnet test -v q online/tests/domain/Interlude.Web.Tests.Domain.fsproj
        
      - name: Build image 
        run: docker build -t interlude-web-server -f online/server/dockerfile .
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DigitalOcean registry 
        run: doctl registry login --expiry-seconds 600
        
      - name: Tag image 
        run:
          docker tag interlude-web-server registry.digitalocean.com/yavsrg/interlude-web-server:latest
          
      - name: Push image
        run: docker push registry.digitalocean.com/yavsrg/interlude-web-server:latest
        
      - name: Run update script on server
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.WEBSERVER_IP }}
            username: root
            password: ${{ secrets.WEBSERVER_PASSWORD }}
            script: ./update.sh
            
      - name: Run garbage collection on DigitalOcean registry
        run: doctl registry garbage-collection start --force --include-untagged-manifests