name: Interlude Release Pipeline Dry-run

on:
  workflow_dispatch:
  # for debug purposes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Package Interlude
      id: package
      run: |
        cd scripts
        chmod +x ./setup_cli.sh
        ./setup_cli.sh
        yavsrg pack_win_x64
        yavsrg pack_linux_x64
        yavsrg pack_osx_x64
        yavsrg pack_osx_arm64
        echo "VERSION=v$(yavsrg version)" >> $GITHUB_OUTPUT
        
    - name: Upload Windows (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: Interlude-win64
          path: ./interlude/releases/Interlude-win64.zip
          
    - name: Upload macOS (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: Interlude-osx-x64
          path: ./interlude/releases/Interlude-osx-x64.zip
          
    - name: Upload macOS (Arm) artifact
      uses: actions/upload-artifact@v4
      with:
          name: Interlude-osx-arm64
          path: ./interlude/releases/Interlude-osx-arm64.zip
          
    - name: Upload Linux (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: Interlude-linux-x64
          path: ./interlude/releases/Interlude-linux-x64.zip