name: Release Interlude

on:
  push:
    branches: [ "main" ]
    paths: "interlude/docs/changelog-latest.md"
  workflow_dispatch:
  # for debug purposes
  
concurrency:
  group: "interlude_release"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository == 'YAVSRG/YAVSRG'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Package Interlude
      id: package
      run: |
        cd scripts
        chmod +x ./setup_cli.sh
        ./setup_cli.sh
        yavsrg pack_win_x64
        yavsrg pack_linux_x64
        echo "VERSION=v$(yavsrg version)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "interlude/releases/*.zip"
        bodyFile: "interlude/docs/changelog-latest.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: YAVSRG
        repo: YAVSRG
        tag: interlude-${{ steps.package.outputs.VERSION }}
        commit: main

    - name: Read changelog contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "interlude/docs/changelog-latest.md"

    - name: Post Changelog via Webhook
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: |
          **New update released!** <@&1147134372504408095>
          ```
          ${{ steps.read_file.outputs.contents }}
          ```
          Update ingame or [download Interlude from GitHub](https://github.com/YAVSRG/YAVSRG/releases/latest/download/Interlude-win64.zip)
