name: MiaouVSRG Release Pipeline Dry-run

on:
  workflow_dispatch:
  # for debug purposes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Package MiaouVSRG
      id: package
      run: |
        cd scripts
        chmod +x ./setup_cli.sh
        ./setup_cli.sh
        miaouvsrg pack_win_x64
        miaouvsrg pack_linux_x64
        miaouvsrg pack_osx_x64
        miaouvsrg pack_osx_arm64
        echo "VERSION=v$(miaouvsrg version)" >> $GITHUB_OUTPUT
        
    - name: Upload Windows (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: MiaouVSRG-win64
          path: ./miaouvsrg/releases/MiaouVSRG-win64.zip
          
    - name: Upload macOS (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: MiaouVSRG-osx-x64
          path: ./miaouvsrg/releases/MiaouVSRG-osx-x64.zip
          
    - name: Upload macOS (Arm) artifact
      uses: actions/upload-artifact@v4
      with:
          name: MiaouVSRG-osx-arm64
          path: ./miaouvsrg/releases/MiaouVSRG-osx-arm64.zip
          
    - name: Upload Linux (x64) artifact
      uses: actions/upload-artifact@v4
      with:
          name: MiaouVSRG-linux-x64
          path: ./miaouvsrg/releases/MiaouVSRG-linux-x64.zip