name: Run unit + integration tests on server
on:
  workflow_dispatch:

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Unit tests
        run: dotnet test -v q online/tests/domain/Interlude.Web.Tests.Domain.fsproj
          
      - name: Setup certificate and secrets for Server instance
        run: |
            mkdir -p online/secrets
            dotnet dev-certs https --trust -ep online/secrets/localhost.pfx -p DEVELOPMENT
            echo "{}" >> online/secrets/secrets.json
        
      - name: Build and run image 
        run: | 
            cd online
            docker compose -p interludeweb up --build --detach
            cd ..
        
      - name: Integration tests
        run: |
            docker logs server
            dotnet test online/tests/integration/Interlude.Web.Tests.Integration.fsproj